In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [2]:
train_df1 = pd.read_csv('train.csv')
train_df2 = train_df1.drop(['id'],axis=1)
train_df2['type'].unique()

array(['BHK2', 'BHK3', 'BHK1', 'RK1', 'BHK4', 'BHK4PLUS'], dtype=object)

In [3]:
type_dummies = pd.get_dummies(train_df2['type'])
train_df3 = pd.concat([type_dummies,train_df2],axis=1)
train_df4 = train_df3.drop('type',axis=1)
train_df4

,BHK1,BHK2,BHK3,BHK4,BHK4PLUS,RK1,locality,activation_date,latitude,longitude,...,bathroom,facing,cup_board,floor,total_floor,amenities,water_supply,building_type,balconies,rent
0,0,1,0,0,0,0,"Cauvery Colony,Koramangala",21-04-2018 14:44,12.934471,77.634471,...,2,E,2,6,12,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",CORP_BORE,AP,2,40000
1,0,1,0,0,0,0,Bellandur,09-10-2017 12:48,12.929557,77.672280,...,2,NE,2,3,4,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",CORPORATION,AP,2,22000
2,0,0,1,0,0,0,Thiruvanmiyur,12-06-2018 22:02,12.982870,80.262012,...,3,E,3,1,5,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",CORP_BORE,AP,3,28000
3,1,0,0,0,0,0,Attiguppe,20-07-2018 16:22,12.955991,77.531634,...,1,E,1,1,2,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,0,8000
4,0,0,1,0,0,0,Kodihalli,31-05-2018 17:41,12.963903,77.649446,...,3,E,4,0,0,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,1,45000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20495,0,0,1,0,0,0,"Gattigere,RR Nagar",13-12-2017 18:08,12.925380,77.524397,...,3,E,3,4,4,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",BOREWELL,AP,2,25000
20496,0,1,0,0,0,0,Koramangala 4th Block,19-10-2017 20:31,12.931072,77.632361,...,2,N,2,1,2,"{""LIFT"":false,""GYM"":false,""INTERNET"":true,""AC""...",CORPORATION,IH,2,30000
20497,0,1,0,0,0,0,Kumaraswamy Layout,21-12-2017 21:18,12.901800,77.566597,...,2,W,2,5,5,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",BOREWELL,AP,2,16000
20498,0,1,0,0,0,0,Indiranagar,28-06-2018 21:58,12.965502,77.647694,...,2,E,2,2,4,"{""LIFT"":true,""GYM"":false,""INTERNET"":true,""AC"":...",CORP_BORE,AP,3,30000
20499,1,0,0,0,0,0,Malleshwaram West,08-07-2018 22:31,12.998645,77.574336,...,1,E,1,1,1,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,1,8500

In [4]:
len(train_df4['locality'].unique())

1938

In [5]:
locality_dummies = pd.get_dummies(train_df4['locality'])
train_df5 = pd.concat([locality_dummies,train_df4],axis=1)
train_df5

,"4th Cross Road, 2nd Stage, Brigade Metropolis, Garudachar Palya, Mahadevapura, Bengaluru, Karnataka 560048, India,Bengaluru","59/35Banashankari 3rd Stage, Banashankari, Bengaluru, Karnataka, India","# 571, 11th &#39;A&#39; cross 31st Main Rd, Sector 1, neyr by C C DAY, 1st Sector, HSR Layout, Bengaluru, Karnataka 560102, India,Bengaluru","#610,5th cross, Bhuvaneshwari layout, , Marathahalli post, Bangalore-560037, 610, 5th Cross Road, Thubarahalli, Marathahalli, Bengaluru, Karnataka 560037, India,Bengaluru","#76 Siva niwas, Vibgyor High School Rd, Silver Springs Layout, Munnekollal, Bengaluru, Karnataka 560066, India,Bengaluru",#8 1st main. 4th cross Bhuvaneshwari nagar. c.v Ramannagar Bangalore 560093. opp konda residency,"1, Kariyammana Agrahara Rd, Kadubeesanahalli, Marathahalli, Bengaluru, Karnataka 560037, India,Bengaluru","10, 5th A Cross Rd, Lakshmi Layout, Gandhi Nagar, Munnekollal, Bengaluru, Karnataka 560037, India,Bengaluru","10/11th Cross Road, Varsova Layout, Kaggadasapura","100 Feet Road, Madiwala, 1st Stage, Indiranagar, Bengaluru, Karnataka, India",...,bathroom,facing,cup_board,floor,total_floor,amenities,water_supply,building_type,balconies,rent
0,0,0,0,0,0,0,0,0,0,0,...,2,E,2,6,12,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",CORP_BORE,AP,2,40000
1,0,0,0,0,0,0,0,0,0,0,...,2,NE,2,3,4,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",CORPORATION,AP,2,22000
2,0,0,0,0,0,0,0,0,0,0,...,3,E,3,1,5,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",CORP_BORE,AP,3,28000
3,0,0,0,0,0,0,0,0,0,0,...,1,E,1,1,2,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,0,8000
4,0,0,0,0,0,0,0,0,0,0,...,3,E,4,0,0,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,1,45000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20495,0,0,0,0,0,0,0,0,0,0,...,3,E,3,4,4,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",BOREWELL,AP,2,25000
20496,0,0,0,0,0,0,0,0,0,0,...,2,N,2,1,2,"{""LIFT"":false,""GYM"":false,""INTERNET"":true,""AC""...",CORPORATION,IH,2,30000
20497,0,0,0,0,0,0,0,0,0,0,...,2,W,2,5,5,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",BOREWELL,AP,2,16000
20498,0,0,0,0,0,0,0,0,0,0,...,2,E,2,2,4,"{""LIFT"":true,""GYM"":false,""INTERNET"":true,""AC"":...",CORP_BORE,AP,3,30000
20499,0,0,0,0,0,0,0,0,0,0,...,1,E,1,1,1,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,1,8500

In [6]:
train_df5['longitude'].max()

80.26634577

In [7]:
train_df5['lease_type'].unique()

array(['FAMILY', 'ANYONE', 'BACHELOR', 'COMPANY'], dtype=object)

In [8]:
lease_dummies = pd.get_dummies(train_df5['lease_type'])
train_df6 = pd.concat([lease_dummies,train_df5],axis=1)
train_df6

,ANYONE,BACHELOR,COMPANY,FAMILY,"4th Cross Road, 2nd Stage, Brigade Metropolis, Garudachar Palya, Mahadevapura, Bengaluru, Karnataka 560048, India,Bengaluru","59/35Banashankari 3rd Stage, Banashankari, Bengaluru, Karnataka, India","# 571, 11th &#39;A&#39; cross 31st Main Rd, Sector 1, neyr by C C DAY, 1st Sector, HSR Layout, Bengaluru, Karnataka 560102, India,Bengaluru","#610,5th cross, Bhuvaneshwari layout, , Marathahalli post, Bangalore-560037, 610, 5th Cross Road, Thubarahalli, Marathahalli, Bengaluru, Karnataka 560037, India,Bengaluru","#76 Siva niwas, Vibgyor High School Rd, Silver Springs Layout, Munnekollal, Bengaluru, Karnataka 560066, India,Bengaluru",#8 1st main. 4th cross Bhuvaneshwari nagar. c.v Ramannagar Bangalore 560093. opp konda residency,...,bathroom,facing,cup_board,floor,total_floor,amenities,water_supply,building_type,balconies,rent
0,0,0,0,1,0,0,0,0,0,0,...,2,E,2,6,12,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",CORP_BORE,AP,2,40000
1,1,0,0,0,0,0,0,0,0,0,...,2,NE,2,3,4,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",CORPORATION,AP,2,22000
2,0,0,0,1,0,0,0,0,0,0,...,3,E,3,1,5,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",CORP_BORE,AP,3,28000
3,0,0,0,1,0,0,0,0,0,0,...,1,E,1,1,2,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,0,8000
4,0,0,0,1,0,0,0,0,0,0,...,3,E,4,0,0,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,1,45000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20495,1,0,0,0,0,0,0,0,0,0,...,3,E,3,4,4,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",BOREWELL,AP,2,25000
20496,1,0,0,0,0,0,0,0,0,0,...,2,N,2,1,2,"{""LIFT"":false,""GYM"":false,""INTERNET"":true,""AC""...",CORPORATION,IH,2,30000
20497,0,0,0,1,0,0,0,0,0,0,...,2,W,2,5,5,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",BOREWELL,AP,2,16000
20498,0,0,0,1,0,0,0,0,0,0,...,2,E,2,2,4,"{""LIFT"":true,""GYM"":false,""INTERNET"":true,""AC"":...",CORP_BORE,AP,3,30000
20499,1,0,0,0,0,0,0,0,0,0,...,1,E,1,1,1,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,1,8500

In [9]:
train_df6['furnishing'].unique()

array(['SEMI_FURNISHED', 'FULLY_FURNISHED', 'NOT_FURNISHED'], dtype=object)

In [10]:
furnishing_dummies = pd.get_dummies(train_df6['furnishing'])
train_df7 = pd.concat([furnishing_dummies,train_df6],axis=1)
train_df7

,FULLY_FURNISHED,NOT_FURNISHED,SEMI_FURNISHED,ANYONE,BACHELOR,COMPANY,FAMILY,"4th Cross Road, 2nd Stage, Brigade Metropolis, Garudachar Palya, Mahadevapura, Bengaluru, Karnataka 560048, India,Bengaluru","59/35Banashankari 3rd Stage, Banashankari, Bengaluru, Karnataka, India","# 571, 11th &#39;A&#39; cross 31st Main Rd, Sector 1, neyr by C C DAY, 1st Sector, HSR Layout, Bengaluru, Karnataka 560102, India,Bengaluru",...,bathroom,facing,cup_board,floor,total_floor,amenities,water_supply,building_type,balconies,rent
0,0,0,1,0,0,0,1,0,0,0,...,2,E,2,6,12,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",CORP_BORE,AP,2,40000
1,0,0,1,1,0,0,0,0,0,0,...,2,NE,2,3,4,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",CORPORATION,AP,2,22000
2,0,0,1,0,0,0,1,0,0,0,...,3,E,3,1,5,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",CORP_BORE,AP,3,28000
3,0,0,1,0,0,0,1,0,0,0,...,1,E,1,1,2,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,0,8000
4,0,0,1,0,0,0,1,0,0,0,...,3,E,4,0,0,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,1,45000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20495,0,0,1,1,0,0,0,0,0,0,...,3,E,3,4,4,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",BOREWELL,AP,2,25000
20496,0,0,1,1,0,0,0,0,0,0,...,2,N,2,1,2,"{""LIFT"":false,""GYM"":false,""INTERNET"":true,""AC""...",CORPORATION,IH,2,30000
20497,0,0,1,0,0,0,1,0,0,0,...,2,W,2,5,5,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",BOREWELL,AP,2,16000
20498,0,0,1,0,0,0,1,0,0,0,...,2,E,2,2,4,"{""LIFT"":true,""GYM"":false,""INTERNET"":true,""AC"":...",CORP_BORE,AP,3,30000
20499,0,0,1,1,0,0,0,0,0,0,...,1,E,1,1,1,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,1,8500

In [11]:
train_df7['parking'].unique()

array(['BOTH', 'TWO_WHEELER', 'NONE', 'FOUR_WHEELER'], dtype=object)

In [12]:
parking_dummies = pd.get_dummies(train_df7['parking'])
train_df8 = pd.concat([parking_dummies,train_df7],axis=1)
train_df8

,BOTH,FOUR_WHEELER,NONE,TWO_WHEELER,FULLY_FURNISHED,NOT_FURNISHED,SEMI_FURNISHED,ANYONE,BACHELOR,COMPANY,...,bathroom,facing,cup_board,floor,total_floor,amenities,water_supply,building_type,balconies,rent
0,1,0,0,0,0,0,1,0,0,0,...,2,E,2,6,12,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",CORP_BORE,AP,2,40000
1,1,0,0,0,0,0,1,1,0,0,...,2,NE,2,3,4,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",CORPORATION,AP,2,22000
2,1,0,0,0,0,0,1,0,0,0,...,3,E,3,1,5,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",CORP_BORE,AP,3,28000
3,0,0,0,1,0,0,1,0,0,0,...,1,E,1,1,2,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,0,8000
4,1,0,0,0,0,0,1,0,0,0,...,3,E,4,0,0,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,1,45000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20495,1,0,0,0,0,0,1,1,0,0,...,3,E,3,4,4,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",BOREWELL,AP,2,25000
20496,1,0,0,0,0,0,1,1,0,0,...,2,N,2,1,2,"{""LIFT"":false,""GYM"":false,""INTERNET"":true,""AC""...",CORPORATION,IH,2,30000
20497,1,0,0,0,0,0,1,0,0,0,...,2,W,2,5,5,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",BOREWELL,AP,2,16000
20498,1,0,0,0,0,0,1,0,0,0,...,2,E,2,2,4,"{""LIFT"":true,""GYM"":false,""INTERNET"":true,""AC"":...",CORP_BORE,AP,3,30000
20499,0,0,0,1,0,0,1,1,0,0,...,1,E,1,1,1,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,1,8500

In [13]:
train_df8['water_supply'].unique()

array(['CORP_BORE', 'CORPORATION', 'BOREWELL'], dtype=object)

In [14]:
water_dummies = pd.get_dummies(train_df8['water_supply'])
train_df9 = pd.concat([water_dummies,train_df8],axis=1)
train_df9

,BOREWELL,CORPORATION,CORP_BORE,BOTH,FOUR_WHEELER,NONE,TWO_WHEELER,FULLY_FURNISHED,NOT_FURNISHED,SEMI_FURNISHED,...,bathroom,facing,cup_board,floor,total_floor,amenities,water_supply,building_type,balconies,rent
0,0,0,1,1,0,0,0,0,0,1,...,2,E,2,6,12,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",CORP_BORE,AP,2,40000
1,0,1,0,1,0,0,0,0,0,1,...,2,NE,2,3,4,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",CORPORATION,AP,2,22000
2,0,0,1,1,0,0,0,0,0,1,...,3,E,3,1,5,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",CORP_BORE,AP,3,28000
3,0,1,0,0,0,0,1,0,0,1,...,1,E,1,1,2,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,0,8000
4,0,1,0,1,0,0,0,0,0,1,...,3,E,4,0,0,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,1,45000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20495,1,0,0,1,0,0,0,0,0,1,...,3,E,3,4,4,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",BOREWELL,AP,2,25000
20496,0,1,0,1,0,0,0,0,0,1,...,2,N,2,1,2,"{""LIFT"":false,""GYM"":false,""INTERNET"":true,""AC""...",CORPORATION,IH,2,30000
20497,1,0,0,1,0,0,0,0,0,1,...,2,W,2,5,5,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",BOREWELL,AP,2,16000
20498,0,0,1,1,0,0,0,0,0,1,...,2,E,2,2,4,"{""LIFT"":true,""GYM"":false,""INTERNET"":true,""AC"":...",CORP_BORE,AP,3,30000
20499,0,1,0,0,0,0,1,0,0,1,...,1,E,1,1,1,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,1,8500

In [15]:
train_df9['building_type'].unique()

array(['AP', 'IH', 'IF', 'GC'], dtype=object)

In [16]:
building_dummies = pd.get_dummies(train_df9['building_type'])
train_df10 = pd.concat([building_dummies,train_df9],axis=1)
train_df10

,AP,GC,IF,IH,BOREWELL,CORPORATION,CORP_BORE,BOTH,FOUR_WHEELER,NONE,...,bathroom,facing,cup_board,floor,total_floor,amenities,water_supply,building_type,balconies,rent
0,1,0,0,0,0,0,1,1,0,0,...,2,E,2,6,12,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",CORP_BORE,AP,2,40000
1,1,0,0,0,0,1,0,1,0,0,...,2,NE,2,3,4,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",CORPORATION,AP,2,22000
2,1,0,0,0,0,0,1,1,0,0,...,3,E,3,1,5,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",CORP_BORE,AP,3,28000
3,0,0,0,1,0,1,0,0,0,0,...,1,E,1,1,2,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,0,8000
4,0,0,0,1,0,1,0,1,0,0,...,3,E,4,0,0,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,1,45000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20495,1,0,0,0,1,0,0,1,0,0,...,3,E,3,4,4,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",BOREWELL,AP,2,25000
20496,0,0,0,1,0,1,0,1,0,0,...,2,N,2,1,2,"{""LIFT"":false,""GYM"":false,""INTERNET"":true,""AC""...",CORPORATION,IH,2,30000
20497,1,0,0,0,1,0,0,1,0,0,...,2,W,2,5,5,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",BOREWELL,AP,2,16000
20498,1,0,0,0,0,0,1,1,0,0,...,2,E,2,2,4,"{""LIFT"":true,""GYM"":false,""INTERNET"":true,""AC"":...",CORP_BORE,AP,3,30000
20499,0,0,0,1,0,1,0,0,0,0,...,1,E,1,1,1,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,1,8500

In [17]:
test_df = pd.read_csv('test.csv')

In [18]:
train_df11 = train_df10
train_df11['latitude'] = train_df10['latitude']/max(train_df10['latitude'].max(),test_df['latitude'].min())
train_df11['latitude'].max()

1.0

In [19]:
train_df12 = train_df11
train_df12['longitude'] = train_df11['longitude']/max(train_df11['longitude'].max(),test_df['latitude'].min())
train_df12['longitude'].max()

1.0

In [20]:
print(train_df12['latitude'].min())
print(train_df12['longitude'].min())

0.9923080937278569
0.9655363244275921

In [21]:
max(train_df12['property_size'].max(),test_df.property_size.max())

50000

In [22]:
train_df13 = train_df12
train_df13['property_size'] = train_df13['property_size']/max(train_df12['property_size'].max(),test_df.property_size.max())

In [23]:
train_df13.property_size.max()

1.0

In [24]:
max(train_df13['property_age'].max(),test_df['property_age'].max())
min(train_df13['property_age'].min(),test_df['property_age'].min())

-1

In [25]:
len(train_df13['property_age'].value_counts(-1))

44

In [26]:
len(train_df13)

20500

In [27]:
train_df14 = train_df13[train_df13['property_age']!=-1]
test_df = test_df[test_df['property_age']!=-1]
print(len(test_df))
len(train_df14)

4490

20467

In [28]:
min(train_df14['property_age'])
min(test_df['property_age'])

0

In [29]:
max(train_df14['bathroom'].max(),test_df['bathroom'].max())

34

In [30]:
train_df15 = train_df14
train_df15['property_age']/=max(train_df14['property_age'].max(),test_df['property_age'].max())
test_df['property_age'] = test_df['property_age']/max(train_df14['property_age'].max(),test_df['property_age'].max())

C:\Users\hp\AppData\Local\Temp\ipykernel_16768\2050173394.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df15['property_age']/=max(train_df14['property_age'].max(),test_df['property_age'].max())

In [31]:
train_df15.bathroom.max()

21

In [32]:
train_df16 = train_df15
train_df16['bathroom'] /= max(train_df15['bathroom'].max(),test_df['bathroom'].max())
test_df['bathroom'] /= max(train_df15['bathroom'].max(),test_df['bathroom'].max())

C:\Users\hp\AppData\Local\Temp\ipykernel_16768\2445669210.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df16['bathroom'] /= max(train_df15['bathroom'].max(),test_df['bathroom'].max())

In [33]:
test_df['bathroom'].max()

1.0

In [34]:
train_df16['facing'].unique()

array(['E', 'NE', 'S', 'N', 'SE', 'W', 'NW', 'SW'], dtype=object)

In [35]:
facing_dummies = pd.get_dummies(train_df16['facing'])
train_df17 = pd.concat([facing_dummies,train_df16],axis=1)
train_df17

,E,N,NE,NW,S,SE,SW,W,AP,GC,...,bathroom,facing,cup_board,floor,total_floor,amenities,water_supply,building_type,balconies,rent
0,1,0,0,0,0,0,0,0,1,0,...,0.058824,E,2,6,12,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",CORP_BORE,AP,2,40000
1,0,0,1,0,0,0,0,0,1,0,...,0.058824,NE,2,3,4,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",CORPORATION,AP,2,22000
2,1,0,0,0,0,0,0,0,1,0,...,0.088235,E,3,1,5,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",CORP_BORE,AP,3,28000
3,1,0,0,0,0,0,0,0,0,0,...,0.029412,E,1,1,2,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,0,8000
4,1,0,0,0,0,0,0,0,0,0,...,0.088235,E,4,0,0,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,1,45000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20495,1,0,0,0,0,0,0,0,1,0,...,0.088235,E,3,4,4,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",BOREWELL,AP,2,25000
20496,0,1,0,0,0,0,0,0,0,0,...,0.058824,N,2,1,2,"{""LIFT"":false,""GYM"":false,""INTERNET"":true,""AC""...",CORPORATION,IH,2,30000
20497,0,0,0,0,0,0,0,1,1,0,...,0.058824,W,2,5,5,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",BOREWELL,AP,2,16000
20498,1,0,0,0,0,0,0,0,1,0,...,0.058824,E,2,2,4,"{""LIFT"":true,""GYM"":false,""INTERNET"":true,""AC"":...",CORP_BORE,AP,3,30000
20499,1,0,0,0,0,0,0,0,0,0,...,0.029412,E,1,1,1,"{""LIFT"":false,""GYM"":false,""INTERNET"":false,""AC...",CORPORATION,IH,1,8500

In [36]:
max(test_df['cup_board'].max(),train_df17['cup_board'].max())

48026

In [37]:
train_df18 = train_df17
train_df18['cup_board'] /= max(test_df['cup_board'].max(),train_df17['cup_board'].max())
test_df['cup_board'] /= max(test_df['cup_board'].max(),train_df17['cup_board'].max())

In [38]:
max(test_df['cup_board'].max(),train_df18['cup_board'].max())

1.0

In [39]:
max(train_df18['floor'].max(),test_df['floor'].max())

25

In [40]:
train_df19 = train_df18
train_df19['floor'] /= max(train_df18['floor'].max(),test_df['floor'].max())
test_df['floor'] /= max(train_df18['floor'].max(),test_df['floor'].max())

In [41]:
max(train_df19['floor'].max(),test_df['floor'].max())

1.0

In [42]:
max(train_df19['total_floor'].max(),test_df['total_floor'].max())

50

In [43]:
train_df20 = train_df19
train_df20['total_floor'] /= max(train_df19['total_floor'].max(),test_df['total_floor'].max())
test_df['total_floor'] /= max(train_df19['total_floor'].max(),test_df['total_floor'].max())

In [44]:
max(train_df20['total_floor'].max(),test_df['total_floor'].max())

1.0

In [45]:
max(train_df20['balconies'].max(),test_df['balconies'].max())

22

In [46]:
train_df21 = train_df20
train_df21['balconies'] /= max(train_df20['balconies'].max(),test_df['balconies'].max())
test_df['balconies'] /= max(train_df20['balconies'].max(),test_df['balconies'].max())

In [47]:
max(train_df19['balconies'].max(),test_df['balconies'].max())

1.0

In [48]:
train_df22 = train_df21.drop(['locality','activation_date','amenities','lease_type','furnishing','parking','facing','water_supply','building_type'],axis=1)
train_df22

,E,N,NE,NW,S,SE,SW,W,AP,GC,...,swimming_pool,negotiable,property_size,property_age,bathroom,cup_board,floor,total_floor,balconies,rent
0,1,0,0,0,0,0,0,0,1,0,...,1,0,0.025,0.025025,0.058824,0.000042,0.24,0.24,0.090909,40000
1,0,0,1,0,0,0,0,0,1,0,...,0,1,0.028,0.004004,0.058824,0.000042,0.12,0.08,0.090909,22000
2,1,0,0,0,0,0,0,0,1,0,...,0,0,0.027,0.006006,0.088235,0.000062,0.04,0.10,0.136364,28000
3,1,0,0,0,0,0,0,0,0,0,...,0,1,0.012,0.003003,0.029412,0.000021,0.04,0.04,0.000000,8000
4,1,0,0,0,0,0,0,0,0,0,...,0,1,0.030,0.015015,0.088235,0.000083,0.00,0.00,0.045455,45000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20495,1,0,0,0,0,0,0,0,1,0,...,1,1,0.033,0.001001,0.088235,0.000062,0.16,0.08,0.090909,25000
20496,0,1,0,0,0,0,0,0,0,0,...,0,1,0.020,0.010010,0.058824,0.000042,0.04,0.04,0.090909,30000
20497,0,0,0,0,0,0,0,1,1,0,...,0,1,0.020,0.000000,0.058824,0.000042,0.20,0.10,0.090909,16000
20498,1,0,0,0,0,0,0,0,1,0,...,0,0,0.020,0.005005,0.058824,0.000042,0.08,0.08,0.136364,30000
20499,1,0,0,0,0,0,0,0,0,0,...,0,1,0.010,0.003003,0.029412,0.000021,0.04,0.02,0.045455,8500

In [49]:
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_train = scaler.fit_transform(train_df22)
multiplied_by = scaler.scale_[1983]
added = scaler.min_[1983]
multiplied_by

2.380952380952381e-05

In [50]:
scaled_train.shape

(20467, 1984)

In [51]:
scaled_train_df = pd.DataFrame(scaled_train, columns=train_df22.columns.values)

In [52]:
scaled_train_df

,E,N,NE,NW,S,SE,SW,W,AP,GC,...,swimming_pool,negotiable,property_size,property_age,bathroom,cup_board,floor,total_floor,balconies,rent
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.024980,0.0625,0.05,0.000042,0.24,0.461538,0.153846,0.761905
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.027981,0.0100,0.05,0.000042,0.12,0.153846,0.153846,0.333333
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.026981,0.0150,0.10,0.000062,0.04,0.192308,0.230769,0.476190
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.011980,0.0075,0.00,0.000021,0.04,0.076923,0.000000,0.000000
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.029981,0.0375,0.10,0.000083,0.00,0.000000,0.076923,0.880952
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20462,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,1.0,0.032981,0.0025,0.10,0.000062,0.16,0.153846,0.153846,0.404762
20463,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.019980,0.0250,0.05,0.000042,0.04,0.076923,0.153846,0.523810
20464,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.019980,0.0000,0.05,0.000042,0.20,0.192308,0.153846,0.190476
20465,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.019980,0.0125,0.05,0.000042,0.08,0.153846,0.230769,0.523810
20466,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.009980,0.0075,0.00,0.000021,0.04,0.038462,0.076923,0.011905

In [ ]:
model = Sequential()

model.add(Dense(50, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(1))

model.compile(loss='mean_squared_error', optimizer='adam')

In [54]:
X = scaled_train_df.drop('rent', axis=1).values
Y = scaled_train_df[['rent']].values

# Train the model
model.fit(
    X[10:],
    Y[10:],
    epochs=10,
    shuffle=True,
    verbose=2
)

Epoch 1/10

KeyboardInterrupt:

In [ ]:
prediction = model.predict(X[:1])
y_0 = prediction[0][0]
print('Prediction with scaling - {}',format(y_0))
y_0 -= added
y_0 /= multiplied_by
print("Housing Price Prediction  - ${}".format(y_0))

In [ ]:
x = Y[:1]
x -= added
x /= multiplied_by
x

In [ ]:
model.save('at_1')